/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as Char91DotwellKnownChar93OauthAuthorizationServerRouteImport } from './routes/[.well-known]/oauth-authorization-server'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDocsSplatRouteImport } from './routes/api/docs/$'
import { Route as ApiDocsOpenapiJsonRouteImport } from './routes/api/docs/openapi-json'
import { Route as ApiMcpIndexRouteImport } from './routes/api/mcp/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiMcpOauthAuthorizeRouteImport } from './routes/api/mcp/oauth/authorize'
import { Route as ApiMcpOauthRegisterRouteImport } from './routes/api/mcp/oauth/register'
import { Route as ApiMcpOauthTokenRouteImport } from './routes/api/mcp/oauth/token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthAuthorizationServerRoute =
  Char91DotwellKnownChar93OauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsSplatRoute = ApiDocsSplatRouteImport.update({
  id: '/api/docs/$',
  path: '/api/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsOpenapiJsonRoute = ApiDocsOpenapiJsonRouteImport.update({
  id: '/api/docs/openapi-json',
  path: '/api/docs/openapi-json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpIndexRoute = ApiMcpIndexRouteImport.update({
  id: '/api/mcp/',
  path: '/api/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpOauthAuthorizeRoute = ApiMcpOauthAuthorizeRouteImport.update({
  id: '/api/mcp/oauth/authorize',
  path: '/api/mcp/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpOauthRegisterRoute = ApiMcpOauthRegisterRouteImport.update({
  id: '/api/mcp/oauth/register',
  path: '/api/mcp/oauth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpOauthTokenRoute = ApiMcpOauthTokenRouteImport.update({
  id: '/api/mcp/oauth/token',
  path: '/api/mcp/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/docs/$': typeof ApiDocsSplatRoute
  '/api/docs/openapi-json': typeof ApiDocsOpenapiJsonRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/mcp/': typeof ApiMcpIndexRoute
  '/api/mcp/oauth/authorize': typeof ApiMcpOauthAuthorizeRoute
  '/api/mcp/oauth/register': typeof ApiMcpOauthRegisterRoute
  '/api/mcp/oauth/token': typeof ApiMcpOauthTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/docs/$': typeof ApiDocsSplatRoute
  '/api/docs/openapi-json': typeof ApiDocsOpenapiJsonRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/mcp': typeof ApiMcpIndexRoute
  '/api/mcp/oauth/authorize': typeof ApiMcpOauthAuthorizeRoute
  '/api/mcp/oauth/register': typeof ApiMcpOauthRegisterRoute
  '/api/mcp/oauth/token': typeof ApiMcpOauthTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/docs/$': typeof ApiDocsSplatRoute
  '/api/docs/openapi-json': typeof ApiDocsOpenapiJsonRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/mcp/': typeof ApiMcpIndexRoute
  '/api/mcp/oauth/authorize': typeof ApiMcpOauthAuthorizeRoute
  '/api/mcp/oauth/register': typeof ApiMcpOauthRegisterRoute
  '/api/mcp/oauth/token': typeof ApiMcpOauthTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/api/$'
    | '/api/auth/$'
    | '/api/docs/$'
    | '/api/docs/openapi-json'
    | '/api/rpc/$'
    | '/api/mcp/'
    | '/api/mcp/oauth/authorize'
    | '/api/mcp/oauth/register'
    | '/api/mcp/oauth/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/api/$'
    | '/api/auth/$'
    | '/api/docs/$'
    | '/api/docs/openapi-json'
    | '/api/rpc/$'
    | '/api/mcp'
    | '/api/mcp/oauth/authorize'
    | '/api/mcp/oauth/register'
    | '/api/mcp/oauth/token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/api/$'
    | '/api/auth/$'
    | '/api/docs/$'
    | '/api/docs/openapi-json'
    | '/api/rpc/$'
    | '/api/mcp/'
    | '/api/mcp/oauth/authorize'
    | '/api/mcp/oauth/register'
    | '/api/mcp/oauth/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  Char91DotwellKnownChar93OauthAuthorizationServerRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocsSplatRoute: typeof ApiDocsSplatRoute
  ApiDocsOpenapiJsonRoute: typeof ApiDocsOpenapiJsonRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiMcpIndexRoute: typeof ApiMcpIndexRoute
  ApiMcpOauthAuthorizeRoute: typeof ApiMcpOauthAuthorizeRoute
  ApiMcpOauthRegisterRoute: typeof ApiMcpOauthRegisterRoute
  ApiMcpOauthTokenRoute: typeof ApiMcpOauthTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/$': {
      id: '/api/docs/$'
      path: '/api/docs/$'
      fullPath: '/api/docs/$'
      preLoaderRoute: typeof ApiDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/openapi-json': {
      id: '/api/docs/openapi-json'
      path: '/api/docs/openapi-json'
      fullPath: '/api/docs/openapi-json'
      preLoaderRoute: typeof ApiDocsOpenapiJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/': {
      id: '/api/mcp/'
      path: '/api/mcp'
      fullPath: '/api/mcp/'
      preLoaderRoute: typeof ApiMcpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/oauth/authorize': {
      id: '/api/mcp/oauth/authorize'
      path: '/api/mcp/oauth/authorize'
      fullPath: '/api/mcp/oauth/authorize'
      preLoaderRoute: typeof ApiMcpOauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/oauth/register': {
      id: '/api/mcp/oauth/register'
      path: '/api/mcp/oauth/register'
      fullPath: '/api/mcp/oauth/register'
      preLoaderRoute: typeof ApiMcpOauthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/oauth/token': {
      id: '/api/mcp/oauth/token'
      path: '/api/mcp/oauth/token'
      fullPath: '/api/mcp/oauth/token'
      preLoaderRoute: typeof ApiMcpOauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  Char91DotwellKnownChar93OauthAuthorizationServerRoute:
    Char91DotwellKnownChar93OauthAuthorizationServerRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocsSplatRoute: ApiDocsSplatRoute,
  ApiDocsOpenapiJsonRoute: ApiDocsOpenapiJsonRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiMcpIndexRoute: ApiMcpIndexRoute,
  ApiMcpOauthAuthorizeRoute: ApiMcpOauthAuthorizeRoute,
  ApiMcpOauthRegisterRoute: ApiMcpOauthRegisterRoute,
  ApiMcpOauthTokenRoute: ApiMcpOauthTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
