/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDocsRouteImport } from './routes/api/docs'
import { Route as ApiDocsOpenapiJsonRouteImport } from './routes/api/docs.openapi-json'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsOpenapiJsonRoute = ApiDocsOpenapiJsonRouteImport.update({
  id: '/openapi-json',
  path: '/openapi-json',
  getParentRoute: () => ApiDocsRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/docs': typeof ApiDocsRouteWithChildren
  '/api/docs/openapi-json': typeof ApiDocsOpenapiJsonRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/docs': typeof ApiDocsRouteWithChildren
  '/api/docs/openapi-json': typeof ApiDocsOpenapiJsonRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/docs': typeof ApiDocsRouteWithChildren
  '/api/docs/openapi-json': typeof ApiDocsOpenapiJsonRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/docs' | '/api/docs/openapi-json' | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/docs' | '/api/docs/openapi-json' | '/api/rpc/$'
  id: '__root__' | '/' | '/api/docs' | '/api/docs/openapi-json' | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRouteWithChildren
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/openapi-json': {
      id: '/api/docs/openapi-json'
      path: '/openapi-json'
      fullPath: '/api/docs/openapi-json'
      preLoaderRoute: typeof ApiDocsOpenapiJsonRouteImport
      parentRoute: typeof ApiDocsRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiDocsRouteChildren {
  ApiDocsOpenapiJsonRoute: typeof ApiDocsOpenapiJsonRoute
}

const ApiDocsRouteChildren: ApiDocsRouteChildren = {
  ApiDocsOpenapiJsonRoute: ApiDocsOpenapiJsonRoute,
}

const ApiDocsRouteWithChildren =
  ApiDocsRoute._addFileChildren(ApiDocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRouteWithChildren,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
