import { exportAccountData } from "@/features/account-data/server/account-data-procedures";
import {
	createNode,
	createStatus,
	createTag,
	deleteNode,
	deleteStatus,
	deleteTag,
	duplicateNode,
	getNode,
	getNodeAncestors,
	listDueSoon,
	listNodes,
	listStatuses,
	listTags,
	moveNode,
	quickOpen,
	renameTag,
	resolveNodeSlug,
	restoreNode,
	setNodeBoardView,
	setNodeColor,
	setNodeDueDate,
	setNodeIcon,
	setNodePriority,
	setNodeRecurrence,
	setNodeStatus,
	setNodeTags,
	setNodeType,
	setTaskCompleted,
	toggleNodeExpanded,
	updateNodeContent,
	updateStatus,
	visibleTree,
} from "@/features/nodes/server/procedures";
import { replayOnboardingTour } from "@/features/onboarding/server/procedures/replay-onboarding-tour";
import {
	getPremiumStatus,
	requestPremiumSeat,
	revokePremiumSeat,
} from "@/features/premium/server/premium-procedures";
import {
	listSessions,
	revokeOtherSessions,
	revokeSession,
} from "@/features/sessions/server/session-procedures";
import {
	getSettings,
	updateSettings,
} from "@/features/settings/server/settings-procedures";
import {
	getTreeHistoryEntry,
	listTreeHistory,
	restoreTreeHistoryEntry,
} from "@/features/tree-history/server/procedures";

export default {
	accountData: {
		export: exportAccountData,
	},
	nodes: {
		list: listNodes,
		get: getNode,
		resolveSlug: resolveNodeSlug,
		ancestors: getNodeAncestors,
		visibleTree,
		listDueSoon,
		quickOpen,
		create: createNode,
		createTag,
		move: moveNode,
		toggleExpanded: toggleNodeExpanded,
		setBoardView: setNodeBoardView,
		delete: deleteNode,
		restore: restoreNode,
		duplicate: duplicateNode,
		updateContent: updateNodeContent,
		setType: setNodeType,
		setDueDate: setNodeDueDate,
		setIcon: setNodeIcon,
		setColor: setNodeColor,
		setRecurrence: setNodeRecurrence,
		setTaskCompleted,
		setTags: setNodeTags,
		setPriority: setNodePriority,
		setStatus: setNodeStatus,
		listStatuses,
		createStatus,
		updateStatus,
		deleteStatus,
		listTags,
		renameTag,
		deleteTag,
	},
	settings: {
		get: getSettings,
		update: updateSettings,
	},
	onboarding: {
		replay: replayOnboardingTour,
	},
	sessions: {
		list: listSessions,
		revoke: revokeSession,
		revokeOthers: revokeOtherSessions,
	},
	premium: {
		get: getPremiumStatus,
		requestSeat: requestPremiumSeat,
		revokeSeat: revokePremiumSeat,
	},
	treeHistory: {
		list: listTreeHistory,
		get: getTreeHistoryEntry,
		restore: restoreTreeHistoryEntry,
	},
};
