import { createFileRoute } from "@tanstack/react-router";
import { Footer } from "#/components/marketing/footer";
import { Nav } from "#/components/marketing/nav";
import { seoHead } from "#/lib/seo";

export const Route = createFileRoute("/privacy")({
	head: () =>
		seoHead(
			"Privacy Policy - Cascade",
			"How Cascade collects, uses, and protects your data.",
			"/privacy",
		),
	component: Privacy,
});

function Privacy() {
	return (
		<>
			<Nav />
			<main className="prose mx-auto max-w-3xl p-8 min-h-128">
				<h1 className="font-serif text-4xl italic mb-2">Privacy Policy</h1>
				<p className="text-sm text-graphite">Last updated: July 7, 2026</p>

				<p>
					This Privacy Policy explains how Cascade ("we", "us") collects, uses,
					and protects your information when you use our application.
				</p>

				<h2>Information we collect</h2>
				<p>
					We collect the information you provide when creating an account (such
					as your name and email address), and information generated by your use
					of the app (such as the content you create and store in Cascade). If
					you sign in with a third-party provider (e.g. GitHub or Google), we
					receive basic profile information from that provider.
				</p>

				<h2>How we use your information</h2>
				<p>
					We use your information to provide and improve the service,
					authenticate you, communicate with you about your account, and comply
					with legal obligations. We do not sell your personal data.
				</p>

				<h2>Data storage and security</h2>
				<p>
					Your data is stored on secure infrastructure and we take reasonable
					technical and organizational measures to protect it against
					unauthorized access, loss, or misuse.
				</p>

				<h2>Cookies</h2>
				<p>
					We use cookies and similar technologies as necessary to operate the
					service, such as keeping you signed in.
				</p>

				<h2>Your rights</h2>
				<p>
					You may access, correct, or delete your personal data at any time by
					contacting us. You may also request a copy of your data or ask us to
					stop processing it, subject to applicable law.
				</p>

				<h2>Changes to this policy</h2>
				<p>
					We may update this policy from time to time. Material changes will be
					communicated by posting the updated policy on this page.
				</p>

				<h2>Contact</h2>
				<p>
					Questions about this policy? Email us at{" "}
					<a href="mailto:contact@patrickroelofs.com">
						contact@patrickroelofs.com
					</a>
					.
				</p>
			</main>
			<Footer />
		</>
	);
}
