import {
	createNode,
	deleteNode,
	getNode,
	getNodeAncestors,
	listNodes,
	moveNode,
	setNodeType,
	toggleNodeExpanded,
	updateNodeContent,
	visibleTree,
} from "@/core/nodes/node.procedures";
import {
	attachTag,
	createTag,
	deleteTag,
	detachTag,
	getNodesForTag,
	getTagsForNode,
	listTags,
	moveTag,
	renameTag,
	setTagColor,
} from "@/core/tags/tag.procedures";

export default {
	nodes: {
		list: listNodes,
		get: getNode,
		ancestors: getNodeAncestors,
		visibleTree,
		create: createNode,
		move: moveNode,
		toggleExpanded: toggleNodeExpanded,
		delete: deleteNode,
		updateContent: updateNodeContent,
		setType: setNodeType,
	},
	tags: {
		list: listTags,
		create: createTag,
		rename: renameTag,
		setColor: setTagColor,
		move: moveTag,
		delete: deleteTag,
		forNode: getTagsForNode,
		nodesForTag: getNodesForTag,
		attach: attachTag,
		detach: detachTag,
	},
};
