import {
	createNode,
	deleteNode,
	deleteTag,
	getNode,
	getNodeAncestors,
	listNodes,
	listTagNames,
	moveNode,
	resolveNodeSlug,
	setNodeDueDate,
	setNodeTags,
	setNodeType,
	toggleNodeExpanded,
	updateNodeContent,
	visibleTree,
} from "@/core/nodes/node.procedures";

export default {
	nodes: {
		list: listNodes,
		get: getNode,
		resolveSlug: resolveNodeSlug,
		ancestors: getNodeAncestors,
		visibleTree,
		create: createNode,
		move: moveNode,
		toggleExpanded: toggleNodeExpanded,
		delete: deleteNode,
		updateContent: updateNodeContent,
		setType: setNodeType,
		setDueDate: setNodeDueDate,
		setTags: setNodeTags,
		tagNames: listTagNames,
		deleteTag,
	},
};
