import {
	bulkAddTag,
	bulkDeleteNodes,
	bulkMoveNodes,
	bulkRemoveTag,
	bulkSetNodeDueDate,
	createNode,
	deleteNode,
	deleteTag,
	getNode,
	getNodeAncestors,
	listNodes,
	listTags,
	moveNode,
	resolveNodeSlug,
	setNodeDueDate,
	setNodeTags,
	setNodeType,
	toggleNodeExpanded,
	updateNodeContent,
	visibleTree,
} from "@/core/nodes/node.procedures";
import {
	getSettings,
	updateSettings,
} from "@/core/settings/settings.procedures";

export default {
	nodes: {
		list: listNodes,
		get: getNode,
		resolveSlug: resolveNodeSlug,
		ancestors: getNodeAncestors,
		visibleTree,
		create: createNode,
		move: moveNode,
		toggleExpanded: toggleNodeExpanded,
		delete: deleteNode,
		updateContent: updateNodeContent,
		setType: setNodeType,
		setDueDate: setNodeDueDate,
		setTags: setNodeTags,
		listTags,
		deleteTag,
		bulkMove: bulkMoveNodes,
		bulkDelete: bulkDeleteNodes,
		bulkAddTag,
		bulkRemoveTag,
		bulkSetDueDate: bulkSetNodeDueDate,
	},
	settings: {
		get: getSettings,
		update: updateSettings,
	},
};
