name: Coolify Deployment Waiter

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  wait-for-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Wait on Coolify Check
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'patrickroelofs'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 15
          allowed-conclusions: success

      - name: Proceed with Next Steps
        run: echo "Coolify deployment is complete! Proceeding..."